### ISSUE TITLE
Enquiry about the size of mpi_b

### ISSUE THREAD

**Issue by derrick-xwp** [nex-mpi/nex-code#17]
Dear author,

From the output of your code, the spatial size of MPI_b is 400 by 400, which is different with the spatial size of other output.

So does your program need interpolation process when rendering on web server?

Why the MPI_b needs to be downsampled during saving, but using same size when training?

Thanks

**Comment by pureexe** [comment]
**Short answer:** Yes, it has interpolation in mpi_b but there has no size during training.

## Explanation

`mpi_b` is H_n  in equation (3) in the paper.

![image](https://user-images.githubusercontent.com/1303847/123078253-fcdae280-d444-11eb-8a51-28bc1ffe1368.png)

During training, the H_n is the network name seq_basis. it isn't **same size when training** because it never has size during training.

https://github.com/nex-mpi/nex-code/blob/eeff38c712ac9a665f09d7c2a3fdf48ae83f4693/train.py#L230

You can set the size of `mpi_b` by change the following line. You will get more accurate H_n but it will take more space to store and transmits over the internet.

https://github.com/nex-mpi/nex-code/blob/eeff38c712ac9a665f09d7c2a3fdf48ae83f4693/train.py#L418-L419


Our NeX-MPI has H_1, H_2, ... H_8. we store H_1, H_2, H_3, and H_4 in `R`, `G`, `B`, and `A` channel of `mpi_b_1.png` respectively.

The viewing direction **v**  is a 3d unit vector where **v** = [v_x,v_y,v_z]. However, when it looks into the mpi_b to get the value of H_n(**v**). it drop v_z and use v_x, v_y to look into the value. you have to scale the pixel coordinate from [0,399] into the range [-0.7, 0.7] on the x-axis and [-0.6,0.6] on the y-axis.  

https://github.com/nex-mpi/nex-code/blob/eeff38c712ac9a665f09d7c2a3fdf48ae83f4693/train.py#L420-L423

The coordinates v_x and v_y might not fall into the exact pixel. We do a bilinear interpolation to get the pixel color value. Then we scale the pixel color value from [0,255] to [-1,1] to be H_n

For example, the viewing direction is [0.3, 0.4, 0.866]. We drop the 0.866 and lookup the pixel color at [0.3, 0.4] on all basis (H_1, H_2, ... H_8).

![image](https://user-images.githubusercontent.com/1303847/123082013-cb641600-d448-11eb-891d-5dfa5b0f207b.png)
 
Note that our NeX-MPI supports only face-forwarding scene. So, we can calculate the v_z  from v_z= sqrt(1 - (v_x^2) - (v_y^2)). Therefore, we use only v_x and v_y to query the basis value.

**Comment by derrick-xwp** [comment]
Thanks for your detailed answer.

 v_x, v_y. v_d are viewing directions. v_d is dropped. So v_x and v_y are rescaled to be 0.6 or 0.7. Why do they need to be rescaled to this range?

IF looking into the mpi_b, one viewing direction  [v_x, v_y] should get 8 basis. The 8 basis will apply to all the colors in the photo of this viewing direction.  But from the code running result, the basis (vi in the code) are different. 

So do I missunderstand anything ?

**Comment by derrick-xwp** [comment]
Following the last question, Is 400X400 in MPI_b the basis in hXW (spatial resolution) or viewing direction (angular resolution) ?

**Comment by pureexe** [comment]
**Short answer:**  mpi_b is an angular resolution.

`mpi_b` is a basis function that has viewing direction as a parameter. it has nothing to do with [h x w]. 

I don't understand **The 8 basis will apply to all the colors** that you are mention.  from my guess, you don't understand how we compute the viewing angle. so, I will try to explain it.

Here, we have a camera at point c that looking in to a plane. Point A and Point B are the pixel on the plane that we need to find a viewing direction **V** (vi in the code) to compute the basis. 

The viewing direction of Point A can be computed by (C- A) / ||(C-A)|| 

Even Point A and Point B are on the same plane. Both have different viewing directions. that's why vi is different.

![image](https://user-images.githubusercontent.com/1303847/123515989-1b024600-d6c4-11eb-8a7f-381c468b8852.png)


To be clear, this is how each file represents variables in the equation.
 
![image](https://user-images.githubusercontent.com/1303847/123515014-150a6600-d6c0-11eb-928d-e510ff456d9e.png)


-----

For the rescaling, we try to look into the viewing direction value that we use to look up and found that it never went higher than 0.7 on the x-axis and 0.6 on the y-axis. 

Instead of store the entire data from [-1,1]. we avoid keeping data in the range [-1,0.7) and (0.7,1] that never use to save up space for transmits over the internet.

**Comment by HrsPythonix** [comment]
Hello, I train with your code on a single 2080 with 
`python train.py -scene data/crest_demo -model_dir crest -http -layers 8 -sublayers 4 -hidden 256`
After training, in the run/html folder, 
![image](https://user-images.githubusercontent.com/16586180/124433557-752a9780-dda5-11eb-897a-0347a950e1fd.png)

If mpi_b is the precomputed basis function, why is there only one mpi_b and why is it not colored like you posted?
![image](https://user-images.githubusercontent.com/16586180/124433749-ad31da80-dda5-11eb-9196-1d14b52e8dae.png)

**Comment by pureexe** [comment]
Sorry, my bad. 

We have multiple versions of the code. The version that uses on the website (https://nex-mpi.github.io/viewer/viewer.html?scene=https://pureexe.github.io/food/800) is the color one.

However, for single mpi_b. You can consider that the first 4 channels can combine into an image.

![image](https://user-images.githubusercontent.com/1303847/124451078-3d285200-ddaf-11eb-9654-8416d0915f00.png)

**Comment by HrsPythonix** [comment]
Thanks for your kind reply, I got it.

Also, I feel that the result in the html is worse than the video, what can I do to improve the result in html?

**Comment by derrick-xwp** [comment]
Thanks a lot!
