### ISSUE TITLE
Render depth

### ISSUE THREAD

**Issue by shanemankiw** [nex-mpi/nex-code#28]
First of all, thanks for sharing such a great work. 

I noticed that although there is an option to 'render_depth' in render_video, it seems that depth rendering is not implemented?

**Comment by pureexe** [comment]
`render_depth` is used to render the pseudo depth map to compare with [Deepview](https://augmentedperception.github.io/deepview/) which looks like this.

https://youtu.be/UD7I9gXIVsc?t=267

![image](https://user-images.githubusercontent.com/1303847/130924221-9b3535d8-5e98-414f-87d0-97c440e172d6.png)

It will replace the output color `rgb` from MPI with the depth instead. 


Here is its implementation. 
https://github.com/nex-mpi/nex-code/blob/eeff38c712ac9a665f09d7c2a3fdf48ae83f4693/train.py#L361-L370

However, our depth is quite bad. since it try to represent some reflection (for example in the reflection on the CD) into the plane. So, the pseudo depth map looks wrong. We haven't shown the depth result on the main paper but feel free to compare with it.

**Comment by shanemankiw** [comment]
Oh that's it, I oversaw that. Thank you very much for the reply!

**Comment by TianYinchen56** [comment]
Thanks to the author's answer, but I still have a question, I added -render_depth when I trained the data as well as when I rendered the data. I checked that render_depth was turned on, but the rendered pictures and videos are still ordinary pictures rather than depth pictures, hoping to get an answer from the author, thanks again
