### ISSUE TITLE
Black boundaries in some cases of Shiny dataset

### ISSUE THREAD

**Issue by Totoro97** [nex-mpi/nex-code#49]
Hi, thanks for your great work!

I found there are some black lines in the boundaries of some images, in the Shiny dataset (for example, CD):

![image](https://user-images.githubusercontent.com/6695053/155832961-9fa16390-2362-4257-b398-beb5ecbaac1c.png)

After I resize the image to the target width (1008), the black line still exists:

![image](https://user-images.githubusercontent.com/6695053/155833086-e2bed503-70ab-4f1e-8595-c6c75d8ffa65.png)

Could you help figure out the reason behind this issue? I would like to know if I should remove the boundary pixels during training (and also in testing).

Thank you very much!

**Comment by pureexe** [comment]
My guess is this black border comes from COLMAP's undistort procedure. 

We didn't handle this problem. but I think it should be fine to mask the border out and specify this problem on your report I guess.

If you have a better method for undistort or want to use different padding instead of zero padding to remove the black border. We also provide an image in the `images_distort` directory.

**Comment by Totoro97** [comment]
Got. Thanks very much!
